### ISSUE TITLE
false positive on 2nd release

### ISSUE THREAD

**Issue by Matterhorn56** [KovaaK/InterAccel#19]
specifically 32 bit (oddly not 64 bit) intergui.exe
Windows Defender (win 10)
![false positive](https://user-images.githubusercontent.com/12612637/86501942-51cca700-bd63-11ea-8523-817c161e1a22.png)

**Comment by NextDev65** [comment]
32 bit intergui.exe
Windows Defender (win 10)
![Annotation](https://user-images.githubusercontent.com/12612637/87574800-83fbd400-c694-11ea-99a8-6394e1e3d514.png)
false postive
2.1 release again win10 defender has flagged 32 bit intergui

**Comment by NextDev65** [comment]
closing because first of all I my pc is 64 bit so I delete 32 bit folder anyways
also commented on an already open issue about the false positive
:) thanks to the devs for an awesome app and imo this isnt really a problem so take your time
